# docker-compose.yml

version: "3"

services:
  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning # --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  balance_calculator:
    build: .
    stdin_open: true
    tty: true
    command: python main.py
    network_mode: host
    volumes:
      - .:/stori_card_assessment
volumes:
  cache:
    driver: local